name: Bug report
description: Something is broken or incorrect
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please do not paste API keys, npm tokens, or other secrets.

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you see? Include any error text.
      placeholder: "I ran `rugbyclaw fixtures` and the proxy says unavailable..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Copy/paste the exact commands you ran.
      placeholder: |
        1. npm install -g rugbyclaw
        2. rugbyclaw config
        3. rugbyclaw fixtures
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "Kickoff times should match the official schedule..."
    validations:
      required: true

  - type: textarea
    id: doctor
    attributes:
      label: Diagnostics (`rugbyclaw doctor --json`)
      description: Run `rugbyclaw doctor --json` and paste the output here.
      render: json
      placeholder: |
        {
          "ok": true,
          "version": "0.1.2",
          "mode": "proxy",
          "checks": { }
        }
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: Example: macOS 14.3, Ubuntu 22.04, Windows 11
    validations:
      required: false

  - type: input
    id: timezone
    attributes:
      label: Timezone
      description: Example: America/New_York
    validations:
      required: false

